// Firebase Options placeholder
// lib/firebase_options.dart
// NOTE: This file should be generated by running: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Run `flutterfire configure` to generate this file with your
/// actual Firebase project configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9DLxgr2XGoDWEzSdkVZ36vDU3F3Yl3us',
    appId: '1:150915747323:web:996781499483372d020f5e',
    messagingSenderId: '150915747323',
    projectId: 'quickfit-4f71f',
    authDomain: 'quickfit-4f71f.firebaseapp.com',
    storageBucket: 'quickfit-4f71f.firebasestorage.app',
    measurementId: 'G-K6LT6CRLQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNDr2ICjCvBpF_Sdt3vPNhCVmehlqixm0',
    appId: '1:150915747323:android:477523f6f7051fb6020f5e',
    messagingSenderId: '150915747323',
    projectId: 'quickfit-4f71f',
    storageBucket: 'quickfit-4f71f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlFEftfszgx4DOdx7GPIdbAQ01U_HpMf8',
    appId: '1:150915747323:ios:b01f1bb24cdb4dbf020f5e',
    messagingSenderId: '150915747323',
    projectId: 'quickfit-4f71f',
    storageBucket: 'quickfit-4f71f.firebasestorage.app',
    iosBundleId: 'com.example.quickfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9DLxgr2XGoDWEzSdkVZ36vDU3F3Yl3us',
    appId: '1:150915747323:web:698b8122965748c7020f5e',
    messagingSenderId: '150915747323',
    projectId: 'quickfit-4f71f',
    authDomain: 'quickfit-4f71f.firebaseapp.com',
    storageBucket: 'quickfit-4f71f.firebasestorage.app',
    measurementId: 'G-209N797EYV',
  );
}
